(cl:defpackage custom_msgs-msg
  (:use )
  (:export
   "<POS>"
   "POS"
   "<NAVIGATIONRESULT>"
   "NAVIGATIONRESULT"
   "<NAVIGATIONFEEDBACK>"
   "NAVIGATIONFEEDBACK"
   "<NAVIGATIONACTION>"
   "NAVIGATIONACTION"
   "<NAVIGATIONACTIONGOAL>"
   "NAVIGATIONACTIONGOAL"
   "<NAVIGATIONGOAL>"
   "NAVIGATIONGOAL"
   "<NAVIGATIONACTIONFEEDBACK>"
   "NAVIGATIONACTIONFEEDBACK"
   "<NAVIGATIONACTIONRESULT>"
   "NAVIGATIONACTIONRESULT"
  ))

