/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/papa/Project/rostest/src/custom_msgs/srv/euler.srv
 *
 */


#ifndef CUSTOM_MSGS_MESSAGE_EULERRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_EULERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct eulerResponse_
{
  typedef eulerResponse_<ContainerAllocator> Type;

  eulerResponse_()
    : pos_z(0.0)  {
    }
  eulerResponse_(const ContainerAllocator& _alloc)
    : pos_z(0.0)  {
    }



   typedef float _pos_z_type;
  _pos_z_type pos_z;




  typedef boost::shared_ptr< ::custom_msgs::eulerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::eulerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct eulerResponse_

typedef ::custom_msgs::eulerResponse_<std::allocator<void> > eulerResponse;

typedef boost::shared_ptr< ::custom_msgs::eulerResponse > eulerResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::eulerResponse const> eulerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::eulerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::eulerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'custom_msgs': ['/home/papa/Project/rostest/src/custom_msgs/msg', '/home/papa/Project/rostest/devel/share/custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::eulerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::eulerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::eulerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::eulerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::eulerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::eulerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::eulerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4328dabeb504dd95a9699c512ddf26c";
  }

  static const char* value(const ::custom_msgs::eulerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4328dabeb504dd9ULL;
  static const uint64_t static_value2 = 0x5a9699c512ddf26cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::eulerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/eulerResponse";
  }

  static const char* value(const ::custom_msgs::eulerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::eulerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_z\n\
\n\
";
  }

  static const char* value(const ::custom_msgs::eulerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::eulerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct eulerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::eulerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::eulerResponse_<ContainerAllocator>& v)
  {
    s << indent << "pos_z: ";
    Printer<float>::stream(s, indent + "  ", v.pos_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_EULERRESPONSE_H
