/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/papa/Project/rostest/src/custom_msgs/srv/euler.srv
 *
 */


#ifndef CUSTOM_MSGS_MESSAGE_EULER_H
#define CUSTOM_MSGS_MESSAGE_EULER_H

#include <ros/service_traits.h>


#include <custom_msgs/eulerRequest.h>
#include <custom_msgs/eulerResponse.h>


namespace custom_msgs
{

struct euler
{

typedef eulerRequest Request;
typedef eulerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct euler
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::euler > {
  static const char* value()
  {
    return "0f0e6028382ae8d43564a2ad2bb6f998";
  }

  static const char* value(const ::custom_msgs::euler&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::euler > {
  static const char* value()
  {
    return "custom_msgs/euler";
  }

  static const char* value(const ::custom_msgs::euler&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::eulerRequest> should match 
// service_traits::MD5Sum< ::custom_msgs::euler > 
template<>
struct MD5Sum< ::custom_msgs::eulerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::euler >::value();
  }
  static const char* value(const ::custom_msgs::eulerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::eulerRequest> should match 
// service_traits::DataType< ::custom_msgs::euler > 
template<>
struct DataType< ::custom_msgs::eulerRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::euler >::value();
  }
  static const char* value(const ::custom_msgs::eulerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::eulerResponse> should match 
// service_traits::MD5Sum< ::custom_msgs::euler > 
template<>
struct MD5Sum< ::custom_msgs::eulerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::euler >::value();
  }
  static const char* value(const ::custom_msgs::eulerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::eulerResponse> should match 
// service_traits::DataType< ::custom_msgs::euler > 
template<>
struct DataType< ::custom_msgs::eulerResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::euler >::value();
  }
  static const char* value(const ::custom_msgs::eulerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_EULER_H
